### ISSUE TITLE
Max iteration limit - not returning best answer

### ISSUE THREAD

**Issue by SamuelKocur** [crewAIInc/crewAI#1038]
In [documenation](https://docs.crewai.com/core-concepts/Agents/#agent-attributes) is written: Max Iter is the maximum number of iterations the agent can perform before being forced to give its best answer. 

Why does the agent return: "Agent stopped due to iteration limit or time limit."? Shouldn't it rather try to generate answer based on the context it gathered?

**Comment by Sar2580P** [comment]
It is because, the  agent decides whether this iteration gives a retrieved information through which sub-question can be answered or not ... 

If not, instead of framing the retrieved information to final response, it moves to next iteration. This way, if it ends up seeing awful information after each retrieval iteration... Then it stops the process, apologizing for not being able to find relevant information.

**Comment by Akashrana1001** [comment]
Hit something adjacent to this — CrewAI loop silently burning tokens/cost before you notice.
Built a small open-source circuit breaker that hooks before_llm_call and kills the call before it's dispatched, instead of after the step finishes. Free, MIT: github.com/Akashrana1001/crew-fusebox

Not selling anything here — just curious if this kind of pre-flight blocker would've caught what you hit. or if your root cause (agent hitting the iteration limit repeatedly without ever landing a usable final answer) needed something more specific than a cost gate.
