### ISSUE TITLE
This model's maximum context length is 8192 tokens.

### ISSUE THREAD

**Issue by torvicvasil** [crewAIInc/crewAI#323]
I'm searching for a theme using an agent and the search engine returns a lot of results. How do I limit the amount of tokens? I'm getting this error:
BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 8217 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

I'm using GPT-3.5 from OpenAI API. Is there a way to overcome that problem or to increase the amount of tokens?

**Comment by Adamchanadam** [comment]
try this ?

```python
from langchain_openai import ChatOpenAI

def configure_language_model(model_name):
    """Function to configure the language model. """
    return ChatOpenAI(temperature=0.7, model_name=model_name , max_tokens=8000)

researcher = Agent(
   llm = configure_language_model("gpt-3.5-turbo-0125") 
)
```

**Comment by aliensouls** [comment]
so it's possible to use langchain_openai configs to pass into the llm parameter?  I thought only langchain and langchain-community can be used (in python 3.8 it yells at me when I install langchain and tells to install the langchain-community instead, because of deprecation). Is it also possible to limit the max tokens for local LLMs? what kind of interface the 'llm' param is, it accepts "anything related to llm init params from any APIs and companies"? 😅  kinda cool

**Comment by saifpashaTrigent** [comment]
That won't work in all the cases because there will be again a distribution between Input Tokens and Output Tokens. 
Which will again lead to Context length error.

**Comment by JoseMiracydeSouzaFilho** [comment]
Hello, I´m with  same issue , Do you have any fix ? 

Thanks a lot !

**Comment by saifpashaTrigent** [comment]
Hey John I was able to solve it using the RAG method but It started to
hallucinate.
