### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by gvossos** [crewAIInc/crewAI#328]
Hi, I'm receiving a 'RecursionError: maximum recursion depth exceeded' after I upgraded to v0.19.0 this morning.  Seems like a pydantic error.  I tried downgrding to pydanticv2.6.1 but still breaking.  Anything you can suggest?

**Comment by a50308isel** [comment]
@gvossos are you using crewAI v0.16.3-v0.19.0 and Ollama?

I am, and noticed that the crew/agents are expecting OpenAI models by default and that's causing me that error in one of my implementations, and another error in other implementation which pointed me to that discover

**Comment by gvossos** [comment]
Hi Sofia,

 

Thanks for your note.  

 

Very weird – all was working fine using crewAI v0.16.3 using gpt-4-turbo-preview.  Over the weekend I thought I’d upgrade to crewAI v0.19.0, where the problems began.

 

My experience is that using either gpt-3.5-turbo OR any of the other HuggingFaces  GGUFs, ie (TheBloke/Mistral-7B-Instruct-v0.2-GGUF) with crewAI/Langchain can cause intermittent errors like you’re suggesting.

 

Best,

George.

**Comment by gvossos** [comment]
The following versions of langcahin & pydnatic were working fine with crewAI v0.16.3 BEFORE the upgrade to v0.19.0 (now broken)

- langchain v0.1.6
- langchain-community v0.0.19
- langchain-core v0.1.23
- pydantic  v2.4.2

**Comment by a50308isel** [comment]
@gvossos I've just discovered that my case wasn't anything to do with Ollama, sorry to mistaken you.
I'm in VSCode Terminal and I turned my terminal scrollback to 10000, to reach the beginning of the error, and had to do long debug, all for the same reason: Agents and Tasks I was logging and turning into strings were throwing this error on Pydantic. So if your problem is the same, you must check where are you trying to use these class objects as strings (like logs, prompts, etc...). When using older versions of crewAI I was able to manipulate those objects as strings, and never noticed that. Hope it helps

**Comment by joaomdmoura** [comment]
"ExecursionError: maximum recursion depth exceeded"
This will be fixed in the next version, already fixed locally, should be
out in the next few days, maybe today if I get to finish it.

--
João Moura
@joaomdmoura <http://twitter.com/joaomdmoura>


Em dom., 10 de mar. de 2024 às 15:12, Sofia Fernandes Condesso <
***@***.***> escreveu:

**Comment by gvossos** [comment]
Thanks for the heads-up Sofia.

Joao - you're amazing!  Looking forward to upgradeing next few days and continuing to use this incredilte agent framework.  Thanks so much!
