### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by abdalladorrah** [crewAIInc/crewAI#532]
Hello, i tried to use crewAI to generate Arabic content , although the llm understand and generate Arabic text, but the core of crewAI does not support that, and it leads to nothing response.

I need an arabian version how can I get that?
I can help in translation and supporting Arabic if it in my range of knowledge 
Thanks

**Comment by atb29** [comment]
> Hello, i tried to use crewAI to generate Arabic content , although the llm understand and generate Arabic text, but the core of crewAI does not support that, and it leads to nothing response.
> 
> I need an arabian version how can I get that? I can help in translation and supporting Arabic if it in my range of knowledge Thanks

I have the same problem as you... Is there any way to get around that with crewai??

**Comment by abdalladorrah** [comment]
> > Hello, i tried to use crewAI to generate Arabic content , although the llm understand and generate Arabic text, but the core of crewAI does not support that, and it leads to nothing response.
> > I need an arabian version how can I get that? I can help in translation and supporting Arabic if it in my range of knowledge Thanks
> 
> I have the same problem as you... Is there any way to get around that with crewai??

there is update in crewAI website about language, but i am still in search for how to use it

**Comment by joaomdmoura** [comment]
We are shipping in this new version I'm writing new docs for it, but you will be bale to provide your own translations now! I'll make sure to add the link to the docs here once it's done

**Comment by abdalladorrah** [comment]
> you

Is it the file of en.json located in  translation folder?

**Comment by cbarkinozer** [comment]
There is an "en.json" file inside "C:\myproject\crew\venv\Lib\site-packages\crewai\translations", I copied that file into the same folder and changed its name to "tr.json" and translated the values to Turkish. Later changed the below part in the i18n.py file by adding "utf-8" encoding so it does not throw an exception when it sees a special character:
```py
 try:
            if self.language_file:
                with open(self.language_file, "r", encoding='utf-8') as f:
                    self._translations = json.load(f)
            else:
                dir_path = os.path.dirname(os.path.realpath(__file__))
                prompts_path = os.path.join(
                    dir_path, f"../translations/{self.language}.json"
                )

                with open(prompts_path, "r", encoding='utf-8') as f:
                    self._translations = json.load(f)
```

Even though the project started without a problem, it failed when using a tool. This approach might work with other languages, other translations or other crew.ai implementations. In my opinion, because these translation JSONs include crew.ai's inner working prompts, they should be tested thoroughly and later added by crew.ai. I prefer using English prompts with "answer in <your language>" sentences in all agent and task prompts for now because it works without a problem and LLMs perform better with English prompts.
