### ISSUE TITLE
Issue with langchain community plugin

### ISSUE THREAD

**Issue by idealley** [crewAIInc/crewAI#782]
I cannot install crewai with poetry while it was perfectly working last week. I have the following error:
```
Because no versions of langchain-community match >0.2.5,<0.3.0
 and langchain-community (0.2.5) depends on langchain (>=0.2.5,<0.3.0), langchain-community (>=0.2.5,<0.3.0) requires langchain (>=0.2.5,<0.3.0).
And because crewai[tools] (0.30.11) depends on langchain (>=0.1.10,<0.2.0)
 and no versions of crewai match >0.30.11,<0.31.0, langchain-community (>=0.2.5,<0.3.0) is incompatible with crewai[tools] (>=0.30.11,<0.31.0).
So, because reports depends on both crewai[tools] (^0.30.11) and langchain-community (^0.2.5), version solving failed.
```

**Comment by saqib727** [comment]
there are version conflicts between the packages crewai, langchain-community, and potentially other dependencies (langchain and reports).

**Comment by saqib727** [comment]
crewai[tools] requires langchain version >=0.1.10,<0.2.0.
langchain-community version 0.2.5 requires langchain version >=0.2.5,<0.3.0

**Comment by idealley** [comment]
Can this be upgraded on crew ai side?

**Comment by saqib727** [comment]
I think so. try with the versions in a given range.

**Comment by afc-development** [comment]
I agree we are are also seeing these issues in our installation. 

Because no versions of langchain-community match >0.2.6,<0.3.0
 and langchain-community (0.2.6) depends on langchain (>=0.2.6,<0.3.0), langchain-community (>=0.2.6,<0.3.0) requires langchain (>=0.2.6,<0.3.0).
And because crewai (0.32.2) depends on langchain (>=0.1.10,<0.2.0), langchain-community (>=0.2.6,<0.3.0) is incompatible with crewai (0.32.2).
So, because crew-ai-backend depends on both crewai (0.32.2) and langchain-community (^0.2.6), version solving failed.

The langchain dependency needs to be updated

**Comment by Stephen-Hamilton-C** [comment]
Ran into this issue as well. I was able to resolve it by upgrading `crewai` to 0.36.0
