### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by superphil0** [crewAIInc/crewAI#910]
https://docs.crewai.com/how-to/Start-a-New-CrewAI-Project/
This page links to this url and is broken

https://docs.crewai.com/how-to/Start-a-New-CrewAI-Project/how-to/Installing-CrewAI.md

**Comment by smartdawg** [comment]
https://github.com/joaomdmoura/crewAI/blob/main/docs/how-to/Start-a-New-CrewAI-Project.md
code line 12:`We assume you have already installed CrewAI. If not, please refer to the [installation guide](how-to/Installing-CrewAI.md) to install CrewAI and its dependencies`.

since the Installing-CrewAI.md is in the 'how-to' directory the code tries to send you to: how-to/how-to/...md   I believe the fix is to change line 12 by dropping the how-to:

`We assume you have already installed CrewAI. If not, please refer to the [installation guide](Installing-CrewAI.md) to install CrewAI and its dependencies.`
